{{ if $.Values.xroadSecurityServer.secondary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xroad-securityserver.fullname" . }}-secondary
  labels:
    {{- include "xroad-securityserver-secondary.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xroad-securityserver-secondary.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xroad-securityserver-secondary.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xroad-securityserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PX_NODE_TYPE
              value: 'secondary'
          {{- with $.Values.xroadSecurityServer.secondary.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: message-exch
              containerPort: 5500
            - name: ocsp
              containerPort: 5577
            - name: health
              containerPort: 5588
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with $.Values.xroadSecurityServer.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - name: init-{{ include "xroad-securityserver.fullname" . }}-secondary
          image: curlimages/curl:7.84.0
          command: ['sh', '-c', "until curl -k -s --connect-timeout 5 https://{{ include "xroad-securityserver.fullname" . }}-primary:4000; do echo waiting for {{ include "xroad-securityserver.fullname" . }}-primary service; sleep 5; done"]
      {{- with $.Values.xroadSecurityServer.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
