apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xroad-securityserver.fullname" . }}-secondary
  labels:
    {{- include "xroad-securityserver-secondary.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.xroadSecurityServer.secondaryReplicaCount }}
  selector:
    matchLabels:
      {{- include "xroad-securityserver-secondary.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xroad-securityserver-secondary.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xroad-securityserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PX_NODE_TYPE
              value: 'secondary'
            - name: PX_ENROLL
              value: 'false'
          {{- with $.Values.xroadSecurityServer.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: message-exch
              containerPort: 5500
            - name: ocsp
              containerPort: 5577
            - name: health
              containerPort: 5588
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: health
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: health
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /
              port: health
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 90
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with $.Values.xroadSecurityServer.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $.Values.xroadSecurityServer.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
