apiVersion: v1
kind: Service
metadata:
  name: {{ include "xroad-securityserver.fullname" . }}-internal
  {{- with $.Values.xroadSecurityServer.service.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "xroad-securityserver.labels" . | nindent 4 }}-internal
spec:
  type:  {{ $.Values.xroadSecurityServer.service.internal.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xroad-securityserver-common-service.selectorLabels" . | nindent 4 }}
