apiVersion: v1
kind: Service
metadata:
  name: {{ include "xroad-securityserver.fullname" . }}-primary
  {{- with $.Values.xroadSecurityServer.service.primary.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "xroad-securityserver-primary.labels" . | nindent 4 }}
spec:
  type: {{ $.Values.xroadSecurityServer.service.primary.type }}
  ports:
    - port: 4000
      targetPort: proxy-ui-api
      protocol: TCP
      name: proxy-ui-api
  selector:
    {{- include "xroad-securityserver-primary.selectorLabels" . | nindent 4 }}
