---
apiVersion: v1
kind: Service
metadata:
  name: px-ss-primary
  labels:
    app: px-ss-primary
spec:
  selector:
    app: px-ss-primary
  ports:
    - name: health
      protocol: TCP
      port: 5588
      targetPort: health
---
apiVersion: v1
kind: Service
metadata:
  name: px-ss-proxy-ui-api
  labels:
    app: px-ss-proxy-ui-api
spec:
  type: NodePort
  selector:
    app: px-ss-primary
  ports:
    - name: proxy-ui-api
      protocol: TCP
      port: 30400
      targetPort: proxy-ui-api
      nodePort: 30400
---
apiVersion: v1
kind: Service
metadata:
  name: px-ss-secondary
  labels:
    app: px-ss-secondary
spec:
  selector:
    app: px-ss-secondary
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: px-ss-public
  labels:
    app: px-ss-public
spec:
  type: NodePort
  selector:
    app: px-ss-secondary
  ports:
    - name: message-exch
      protocol: TCP
      port: 30500
      targetPort: message-exch
      nodePort: 30500
    - name: ocsp
      protocol: TCP
      port: 30577
      targetPort: ocsp
      nodePort: 30577
