xroadSecurityServer:
  enroll: true
  env:
    - name: PX_INSTANCE
      value: 'JP-TEST'
    - name: PX_MEMBER_CLASS
      value: 'COM'
    - name: PX_MEMBER_CODE
      value: '0170121212121'
    - name: PX_SS_CODE
      value: 'k8-ss01'
    - name: PX_SS_PUBLIC_ENDPOINT
      value: 'k8-ss01.localdomain'
    - name: PX_TSA_NAME
      value: 'TEST of Planetway Timestamping Authority 2020'
    - name: PX_TSA_URL
      value: 'https://tsa.test.planetcross.net'
    - name: PX_CA_NAME
      value: 'TEST of Planetway Root CA 2021'
    - name: PX_TOKEN_PIN
      value: 'p@ssw0rd123'
    - name: PX_ADMINUI_USER
      value: 'admin'
    - name: PX_ADMINUI_PASSWORD
      value: 'password'
    - name: POSTGRES_HOST
      value: 'postgresql.default.svc.cluster.local'
    - name: POSTGRES_PORT
      value: '5432'
    - name: POSTGRES_USER
      value: 'postgres'
    - name: POSTGRES_PASSWORD
      value: 'secret'
    - name: PX_SERVERCONF_URL
      value: 'jdbc:postgresql://postgresql.default.svc.cluster.local:5432/serverconf'
    - name: PX_MESSAGELOG_URL
      value: 'jdbc:postgresql://postgresql.default.svc.cluster.local:5432/messagelog'
    - name: PX_OPMONITOR_URL
      value: 'jdbc:postgresql://postgresql.default.svc.cluster.local:5432/op-monitor'
    - name: PX_SERVERCONF_PASSWORD
      value: 'secret'
    - name: PX_MESSAGELOG_PASSWORD
      value: 'secret'
    - name: PX_OPMONITOR_PASSWORD
      value: 'secret'
    - name: PX_POPULATE_DATABASE
      value: 'true'
    - name: PX_ENROLL
      value: 'true'
  extraVolumeMounts:
    - name: xroad-securityserver-pv
      mountPath: /etc/xroad/signer
      subPath: signer
    - name: xroad-securityserver-pv
      mountPath: /var/lib/xroad
      subPath: xroad
  extraVolumes:
    - name: xroad-securityserver-pv
      persistentVolumeClaim:
        claimName: xroad-securityserver-pvc
  secondaryReplicaCount: 2
