---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xroad-securityserver-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
